name: deploy
description: deployment action

inputs:
  env:
    required: true
    description: Environment (region, maybe also account?)
  secret_input:
    required: true
    description: Secret

runs:
  using: 'composite'
  steps:
    - run: yarn deploy ${{ inputs.env }}
      shell: bash
      name: Deploy
    - name: Echo secret input
      run: echo ${{ inputs.secret_input }}
      shell: bash