name: deploy
description: deployment action

inputs:
  env:
    required: true
    description: Environment (region, maybe also account?)
  secret_input:
    required: true
    description: Secret

runs:
  using: 'composite'
  steps:
    - run: yarn deploy ${{ inputs.env }}
      shell: bash
      name: Deploy
    - name: embedded-action
      uses: ./.github/actions/embedded-action
      with:
        secret_input: ${{ inputs.secret_input }}