name: Branch-only

on:
  push:
    branches:
      - non-triggerable

jobs:
  promote-deployment:
    name: Promote deployment to prod
    runs-on: ubuntu-latest

    steps:
      - name: Get region
        id: get-region
        uses: actions/github-script@v6
        with:
          script: console.log('stuff')
