name: Deploy Staging workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to staging
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

#      - name: Run static code analysis
#        run: npm run lint
#
#      - name: Run UTs
#        run: npm run test

      - name: build
        run: npm run build

      - name: deploy
        run: npm run deploy

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/index.js"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag: ${{ steps.package-version.outputs.current-version}}
          name: ${{ steps.package-version.outputs.current-version}}