name: Deploy Staging workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to staging
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

#      - name: Run static code analysis
#        run: npm run lint
#
#      - name: Run UTs
#        run: npm run test

      - name: build
        run: yarn build

      - name: deploy
        run: yarn deploy stage

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: region1 release
        id: region1-release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/index.js"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag: region1-${{ steps.package-version.outputs.current-version}}
          name: region1-${{ steps.package-version.outputs.current-version}}

      - name: region2 release
        id: region2-release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/index.js"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag: region2-${{ steps.package-version.outputs.current-version}}
          name: region2-${{ steps.package-version.outputs.current-version}}

      - name: region1 release link
        run: echo "${{ steps.region1-release.outputs.html_url }}"

      - name: region2 release link
        run: echo "${{ steps.region2-release.outputs.html_url }}"