name: Promote to Region prod

on:
  release:
    types: [published]

jobs:
  promote-deployment:
    name: Promote deployment to prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        run: yarn

      - name: Get artifact filename without doublequotes because the action for fetching artifact cannot handle such thing as doublequotes
        id: get-artifact-name
        uses: actions/github-script@v6
        with:
          script: return context.payload.release.assets[0].name
          result-encoding: string

      - name: Get region
        id: get-region
        uses: actions/github-script@v6
        with:
          script: return context.payload.release.name.split('-')[0]
          result-encoding: string

      # TODO: this could use an artifact from GH Actions rather than from a release
      - name: Get artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: ${{ github.event.release.id }}
          file:  ${{ steps.get-artifact-name.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
          regex: true

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          env: ${{ steps.get-region.outputs.result }}
