name: Deploy Staging workflow

on:
  release:
    types: [published]

jobs:
  promote-deployment:
    name: Promote deployment to prod
    runs-on: ubuntu-latest

    steps:
      - name: debug release
        run: echo ${{ github.event.release }}

      - name: release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'dweller23/deploy-with-release-draft-poc' #TODO automate
          version: ${{ github.event.release.id }}
          file: 'index.js'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy
        run: npm run deploy