name: Deploy Staging workflow

on:
  release:
    types: [published]

jobs:
  promote-deployment:
    name: Promote deployment to prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Dump github context
#        run: echo "$GITHUB_CONTEXT"
#        shell: bash
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github).event }}

      - name: release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: ${{ github.event.release.id }}
          file:  ${{ toJson(github).event.release.assets[0].name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy
        run: npm run deploy